branches:
  except:
    - gh-pages
sudo: false
language: perl6
perl6:
  - latest
install:
  - rakudobrew build zef
  - zef --debug --depsonly install .
  - cpanm --notest -q https://github.com/melezhik/outthentic.git
  - PERL5LIB=~/perl5/lib/perl5/:$PERL5LIB PATH=~/perl5/bin:$PATH strun --recu outthentic/
