branches:
  except:
    - gh-pages
sudo: false
language: perl6
perl6:
  - latest
install:
  - rakudobrew build zef
  - zef --debug --depsonly install .
  - cpanm --notest -q https://github.com/melezhik/outthentic.git
  - PERL6LIB=$PWD/lib:$PERL6LIB PERL5LIB=~/perl5/lib/perl5/:$PERL5LIB PATH=$PWD/bin:~/perl5/bin:$PATH strun --recu outthentic/
