branches:
  except:
    - gh-pages
sudo: false
language: perl6
perl6:
  - latest
install:
  - rakudobrew build zef
  - zef --debug --depsonly install .
  - cpanm -q --notest https://github.com/melezhik/outthentic.git
  - strun --recu outthentic/
