branches:
  except:
    - gh-pages
sudo: false
language: perl6
perl6:
  - latest
install:
  - rakudobrew build zef
  - zef --debug --depsonly install .
  - cpanm --notest https://github.com/melezhik/outthentic.git
  - PERL5_LIB=~/perl5/lib/perl5/:$PERL5_LIB PATH=~/perl5/local/bin:$PATH strun --recu outthentic/
